gText_Birch_Welcome::
	.string "A man is rambling in a dark void.\p"
	.string "Your ears are still buzzing, but\n"
	.string "you can pick up the gist.\p"
	.string "He's Birch, a cryptozoologist.\p"
	.string "Wait, are POKéMON cryptids?\p"
	.string "$"

gText_Birch_Pokemon::
	.string "You imagine people taking blurry\n"
	.string "photos of this blue dork.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "He continues, some basic diatribe\n"
	.string "on POKéMON human interactions.\p"
	.string "You don't need to hear this,\n"
	.string "you aren't five, at least you're\l"
	.string "pretty sure about it.\p"
	.string "It's perfectly normal to not know\n"
	.string "how old you are. Stop worrying.\p"
	.string "At least try to pretend to listen\n"
	.string "to Birch. It's polite.\p"
	.string "Sure, you recognize this speech,\n"
	.string "but that doesn't really matter.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "He interrupts your internal conversation\n"
	.string "with an annoyingly pointed question.\p"
	.string "This shit again. Why is it familiar?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?\n"
	.string "Dude, first, you are an adult\p"
	.string "Second, none of your buisiness\p"
	.string "Third, you're not really sure and\n"
	.string "don't want to guess wrong or anything.$"

gText_Birch_WhatsYourName::
	.string "He moves on, clearly tense.\n"
	.string "You're going off script.\p"
	.string "You're a terrible actor.\p"
	.string "In an attempt to salvage this conversation,\n"
	.string "he asks for your name.\p"
	.string "A completely normal and human question,\n"
	.string "it would be weird to not answer it.\p"
	.string "Why aren't you answering it?\p"
	.string "Just make something up if you can't remember it.$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?\p"
	.string "Maybe you can act. This name is\n"
	.string "probably wrong, but it can work.\p"
	.string "At least, until you figure out your\n"
	.string "actual one, which probably exists.$"

gText_Birch_YourePlayer::
	.string "Suddenly, everything hurts more than usual.\p"
	.string "Birch is oblivious. You kinda hate him,\n"
	.string "even though you know it's rude.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "He keeps treating you like you're a kid\p"
	.string "He's all bright and optimistic, while you're\n"
	.string "trying not to hurl. Why does your head burn?\p"
	.string "Why does your body look like a ghost?\n"
	.string "POKéMON this, friendships that, you just\l"
	.string "need to know what's going on.\p"
	.string "Your thoughts are interrupted when\n"
	.string "Birch hits you with his shrinking spell.\p"
	.string "$"
